class Names:
    def __init__(self):
        self.DEFECTIVE: str = "DEFECTIVE"
        self.DATE_ORDER: str = "DATE_ORDER"
        self.CONTACT_DATE: str = "CONTACT_DATE"
        self.CONTACT_TYPE_DETAILS: str = "CONTACT_TYPE_DETAILS"
        self.PRODUCT_CATEGORY: str = "PRODUCT_CATEGORY"
        self.BRAND: str = "BRAND"
        self.MODEL: str = "MODEL"
        self.STATE: str = "STATE"
        self.PRICE: str = "PRICE"
        self.PRICE_NEW: str = "PRICE_NEW"
        self.MERCHANT_ID: str = "MERCHANT_ID"
        self.CUSTOMER_COUNTRY: str = "CUSTOMER_COUNTRY"
        self.MERCHANT_COUNTRY: str = "MERCHANT_COUNTRY"
        self.PRODUCT_RELEASE_DATE: str = "PRODUCT_RELEASE_DATE"
        self.has_contact: str = "has_contact"
        self.NB_DAYS_PROBLEM_START: str = "NB_DAYS_PROBLEM_START"
        self.PRICE_FROM_NEW_PERC: str = "PRICE_FROM_NEW_PERC"
        self.DAYS_SINCE_PRODUCT_RELEASE_DATE: str = "DAYS_SINCE_PRODUCT_RELEASE_DATE"
